version: "3.1"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Rhinebeck2021
    volumes:
      - mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    container_name: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
  adas-web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./config.json:/config.json
    depends_on:
      - mysql
    container_name: adas-web
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - adas-web
    container_name: nginx
    volumes:
      - ./certs/adas.crt:/etc/nginx/certs/ssl.crt
      - ./certs/adas.key:/etc/nginx/certs/ssl.key
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./access.log:/var/log/nginx/
    ports:
      - "443:443"
      - "80:80"
      - "3306:3306"
volumes:
  mysql:
